// src/lib/gemini.ts
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export async function generateAIPostAndPrompt() {
  // 1.5-flash fast hai aur JSON format ke liye behtar hai
  const model = genAI.getGenerativeModel({ 
    model: "gemini-2.5-flash",
    generationConfig: { responseMimeType: "application/json" } // Force Gemini to give JSON
  });

  const prompt = `
  I am a Full Stack Developer and AI Automation Expert. 
  Task: Generate a professional Facebook post text and a high-end 3D advertisement image prompt.

  **1. INSTRUCTIONS FOR POST TEXT (MESSAGE):**
  - Subject: "Abbas AI Solutions" expert services.
  - Tone: Professional, detailed, and authoritative.
  - Content: Explain Full Stack expertise (Next.js, React, SaaS) and AI Automation (ERPs, Custom Agents, Marketing).
  - Must Include: WhatsApp: +923010637955 and placeholders for [https://vercel.com/ghulam-abbas-bhattis-projects] and [https://www.paib.pk/developers/abbas-bhatti].
  - Mention: "This post and the attached advertisement were 100% generated by my AI system."

  **2. INSTRUCTIONS FOR IMAGE GENERATION PROMPT:**
  Create an ultra-realistic, cinematic 3D advertisement layout for "ABBAS AI SOLUTIONS".
  
  **Visible Text on Image (CRITICAL):**
  - Main Title: "ABBAS AI SOLUTIONS" (Bold, glowing neon, top center).
  - Sub-heading: "PREMIUM AI AUTOMATION SERVICES".
  - Top 3 Services (Clear labels): "AUTO MARKETING", "AUTO AGENTS", "CUSTOM SaaS".
  - Automation Proof: A small, elegant badge or footer text saying: "100% AI AUTOMATED POST & IMAGE".
  - Contact: WhatsApp: +923010637955.

  **Visual Elements & Style:**
  - Background: Midnight blue, sleek, futuristic digital command center.
  - Centerpiece: A glowing holographic AI brain or robotic interface representing intelligence.
  - Lighting: Electric cyan and deep purple neon accents, 8k resolution, cinematic blur (bokeh) in the background.
  - Quality: Professional agency level, photorealistic, clean typography, no spelling errors.

  **REQUIRED OUTPUT FORMAT:**
  Return ONLY a JSON object with this exact structure:
  {
    "post_text": "Write the detailed professional message here",
    "image_prompt": "Provide the ultra-detailed visual description for the image generator here"
  }
`;
  try {
    const result = await model.generateContent(prompt);
    const responseText = result.response.text();

    // Markdown ticks ko clean karne ka foolproof tareeqa
    const cleanJson = responseText
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    return JSON.parse(cleanJson);
  } catch (error) {
    console.error("Gemini Error or JSON Parse Error:", error);
    throw new Error("Failed to generate valid content from AI");
  }
}