import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  try {
    // 1. Authorization Check
    const authHeader = request.headers.get('authorization');
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return new NextResponse('Unauthorized', { status: 401 });
    }

    console.log("1. Cron Started: Fetching content...");

    // 2. Gemini AI Content (Example - Aap yahan apni Gemini API call bhi laga sakte hain)
    const aiMessage = "AI Automation is the future! 🤖 Post generated by my AI Agent at " + new Date().toLocaleTimeString();

    // 3. Facebook API Settings (Variables se uthayega)
    const PAGE_ID = process.env.FB_PAGE_ID;
    const ACCESS_TOKEN = process.env.FB_PAGE_ACCESS_TOKEN;

    if (!PAGE_ID || !ACCESS_TOKEN) {
        throw new Error("Facebook Page ID or Access Token is missing in Environment Variables");
    }

    console.log("2. Sending Post to Facebook Page ID:", PAGE_ID);

    // 4. Actual Post Request to Facebook
    const fbResponse = await fetch(`https://graph.facebook.com/v19.0/${PAGE_ID}/feed`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: aiMessage,
        access_token: ACCESS_TOKEN,
      }),
    });

    const result = await fbResponse.json();

    if (result.error) {
      console.error("Facebook API Error Detail:", result.error);
      return NextResponse.json({ success: false, error: result.error.message }, { status: 400 });
    }

    console.log("3. Success! Post ID:", result.id);
    return NextResponse.json({ 
        success: true, 
        message: "Post shared successfully!", 
        id: result.id 
    });

  } catch (error: any) {
    console.error("Final Cron Error:", error.message);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}